### PR TITLE
Update nuget references to 140 version. 

### PR DESCRIPTION
**Pull request by kevcunnane**
note: should re-run strongly typed model code, but leaving as there are issues that need to be resolved before this will build with the new code.

### CODE REVIEW

**Comment by ErikEJ** [comment]
@kevcunnane 
>> should re-run strongly typed model code, but leaving as there are issues that need to be resolved before this will build with the new code.

Does that mean that strongly typed model cannot be used with 140 or?? (Plan to use it in a tool)

**Comment by kevcunnane** [comment]
That's right. The non-strongly typed model is fine but there are some bugs in the internal mappings that cause problems when running this strongly typed model. It'll work against older versions but not the recent one. I'd suggest opening an issue against this, we can at least track the desire to use this and see if we can resolve the blockers in a future Dacfx update.

**Comment by ErikEJ** [comment]
Just to be clear: I can get the latest source, by change all DacFX references to 130 (from 140) in order to use the stringly typed model - is that correct?

**Comment by kevcunnane** [comment]
What is means is you may not be able to use the strongly typed model fully against 130 (SQL2016) or 140 (SQL2017) sources. It hasn't had the T4 templates re-run, so the most up to date set of metadata comes from 120.

You should still be able to run against those target and do queries for existing objects, properties and relationships defined pre-2016, but for newer objects etc. you will have to fall back to the regular (not strongly typed) model.

**Pull request merged**
